apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ventas-app          # Nombre de la aplicación dentro de Argo CD
  namespace: argocd         # Namespace donde corre Argo CD
spec:
  project: default
  source:
    repoURL: 'https://github.com/tu_usuario/ventas-app'  # URL de tu repo GIT
    targetRevision: HEAD                                 # Rama principal (puede ser main o master)
    path: charts/ventas                                   # Ruta donde está el Chart.yaml
  destination:
    server: 'https://kubernetes.default.svc'             # Cluster local (in-cluster)
    namespace: default                                    # Namespace donde se desplegará la app
  syncPolicy:
    automated:                                            # ArgoCD hará sync automáticamente
      prune: true                                         # Elimina recursos que ya no están en Git
      selfHeal: true                                      # Reaplica si hay cambios fuera de Git
