apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
spec:
  type: NodePort
  selector:
    app: {{ .Release.Name }}
  ports:
    - port: 80
      targetPort: 3030  # Este debe ser el puerto donde corre tu app dentro del contenedor
      protocol: TCP
